### PR TITLE
Estonian 6.16.0 2

### PR DESCRIPTION
**Pull request by kristoheero**
* XTE-248 / Backlog #55: Security Server: Fixed creation of signed documents (backward compatible) to follow e-signature standards (XAdES, ASiC).
* XTE-330 / Backlog #127: Security Server: Added support for "NEE" member class in certificates provided by SK ID Solutions AS.
* XTE-357 / Backlog #164: Security Server: Fixed temporary files removal in error situations.

### CODE REVIEW

**Comment by VitaliStupin** [comment]
XTE-248 = Backlog https://github.com/vrk-kpa/xroad-joint-development/issues/55

**Review by VitaliStupin — APPROVED** [review]

**Review by iluwatar — COMMENTED** [review]
Just a couple of questions. There are no documentation related changes. Is the documentation not affected? Do the tools `asicverifier` and `archive-hashchain-verifier.rb` continue working?

**Comment by kristoheero** [comment]
Yes, mentioned tools are working. Changed only digital signature profile (see https://repo.cyber.ee/dsig-profile-1.2.pdf).

**Comment by iluwatar** [comment]
The document has information that is highly relevant to X-Road developers. Could we link the aforementioned document to the security server's user manual https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#11-message-log?

**Comment by iluwatar** [comment]
It was agreed to supplement the documentation later.

**Review by iluwatar — APPROVED** [review]

**Pull request merged**
