### PR TITLE
Documents converted from Microsoft Word format into Github flavoured Markdown

### PR DESCRIPTION
**Pull request by ToomasMolder**
Updated README.md
Added terms_x-road_docs.md

Converted:
[ARC-G] - Architecture/arc-g_x-road_arhitecture.md
[ARC-SS] - Architecture/arc-ss_x-road_security_server_architecture.md
[ARC-CP] - Architecture/arc-cp_x-road_configuration_proxy_architecture.md
[ARC-CS] - Architecture/arc-cs_x-road_central_server_architecture.md
[PR-MESS] - Protocols/pr-mess_x-road_message_protocol.md
[UG-SS] - Manuals/ug-ss_x-road_6_security_server_user_guide.md
[IG-SS] - Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
[IG-CSHA] - Manuals/ig-csha_x-road_6_ha_installation_guide.md
[UC-MEMBER] - UseCases/uc-member_x-road_use_case_model_for_member_management.md
[UC-MESS] - UseCases/uc-mess_x-road_member_communication_use_case_model.md

Images in subdirectories img/
Deleted versions in Microsoft Word format as there is version converted into Markdown.

### CODE REVIEW

**Review by VitaliStupin — APPROVED** [review]

**Comment by VitaliStupin** [comment]
Additionally:

Removed manuals for no longer used UXP monitoring solution:
doc/Manuals/central_monitoring_agent_manual_1.1_Y-745-12.pdf
doc/Manuals/proxy_monitoring_agent_manual_1.1_Y-745-13.pdf

Removed old version of PR-MESS in Lyx format:
doc/Technical/v6_SOAP.zip

Removed no longer up to date testing documentation (in Estonian) and test programs:
doc/Testing/*

This pull request can be combined info one commit if needed.

**Comment by Jevli** [comment]
I did review this Pull Request and we have few change suggestions:
- Linking doesn't follow [styleguide](https://github.com/vrk-kpa/xroad-joint-development/blob/master/FormattingStyleGuide.md), there is no need for ```<div>``` -tags and from my point of view they should not be used.
- Table of contents also doesn't follow styleguide, it should not use ```&nbsp;```, this could be done by using generator like styleguide says.

Please follow styleguide with Markdown documents.

**Comment by ToomasMolder** [comment]
Corrected, i.e removed DIV-s and corrected TOC-s. Also corrected wording of license, changed levels of headers etc.

DIV-s were added previously to keep internal links from TOC into paragraph header functional in PDF version (example: pandoc.exe -s file.md -f markdown-implicit_figures -V geometry:"top=2.5cm, bottom=2.5cm, left=2.5cm, right=1.5cm" -t latex+auto_identifiers -o file.pdf). Did'nt find any other working solution for PDF, these DIV-s were conformant of GFM. NB! Pandoc uses slightly different schema to generate internal links compared with GFM.

Styleguide does not say anything about \&nbsp; not allowed within TOC. From personal view, previous version was better-looking and did'nt contradict with styleguide or GFM.

**Comment by Jevli** [comment]
@iluwatar Pull request is now reviewed and fine. From my point of view this can be accepted and merged.

**Review by iluwatar — APPROVED** [review]

**Pull request merged**
